import type { Metadata } from "next";
import { Arimo } from "next/font/google";
import { cn } from "@/lib/utils";
import "@/style/globals.css";

const arimo = Arimo({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-arimo",
});

export const metadata: Metadata = {
  title: "Healvora",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={arimo.variable}>
      <body className={cn("antialiased font-sans bg-background   ")}>
        {children}
      </body>
    </html>
  );
}
